default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: strange_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: strange_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: strange_production
    username: strange
    password: <%= ENV["STRANGE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: strange_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: strange_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: strange_production_cable
    migrations_paths: db/cable_migrate
