default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: strange_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: strange_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary:
    <<: *default
    adapter: postgresql
    host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    database: <%= ENV.fetch("POSTGRES_DB", "strange_production") %>
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
    pool: 5

  cache:
    <<: *default
    adapter: postgresql
    host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    database: strange_production_cache
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    adapter: postgresql
    host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    database: strange_production_queue
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
    migrations_paths: db/queue_migrate
